//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasCF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flujo
    {
        public int IDFlujo { get; set; }
        public System.DateTime FlujoFecha { get; set; }
        public Nullable<int> IDPersona { get; set; }
        public Nullable<int> IDCategoria { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
